spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
  output:
    ansi:
      enabled: ALWAYS